import { AutoCompleteOption } from "../stories/AutoComplete/AutoComplete";

// 76 movies in the object
export const topMovies: AutoCompleteOption[] = [
    { label: 'The Shawshank Redemption', value: 'The Shawshank Redemption' },
    { label: 'The Godfather', value: 'The Godfather' },
    { label: 'The Godfather: Part II', value: 'The Godfather: Part II' },
    { label: 'The Dark Knight', value: 'The Dark Knight' },
    { label: '12 Angry Men', value: '12 Angry Men' },
    { label: "Schindler's List", value: "Schindler's List" },
    { label: 'The Lord of the Rings: The Return of the King', value: 'The Lord of the Rings: The Return of the King' },
    { label: 'Pulp Fiction', value: 'Pulp Fiction' },
    { label: 'The Good, the Bad and the Ugly', value: 'The Good, the Bad and the Ugly' },
    { label: 'Fight Club', value: 'Fight Club' },
    { label: 'The Lord of the Rings: The Fellowship of the Ring', value: 'The Lord of the Rings: The Fellowship of the Ring' },
    { label: 'Forrest Gump', value: 'Forrest Gump' },
    { label: 'Inception', value: 'Inception' },
    { label: 'The Lord of the Rings: The Two Towers', value: 'The Lord of the Rings: The Two Towers' },
    { label: 'Star Wars: Episode V - The Empire Strikes Back', value: 'Star Wars: Episode V - The Empire Strikes Back' },
    { label: 'The Matrix', value: 'The Matrix' },
    { label: 'Goodfellas', value: 'Goodfellas' },
    { label: 'One Flew Over the Cuckoo\'s Nest', value: 'One Flew Over the Cuckoo\'s Nest' },
    { label: 'Seven Samurai', value: 'Seven Samurai' },
    { label: 'Se7en', value: 'Se7en' },
    { label: 'Life Is Beautiful', value: 'Life Is Beautiful' },
    { label: 'City of God', value: 'City of God' },
    { label: 'The Silence of the Lambs', value: 'The Silence of the Lambs' },
    { label: 'It\'s a Wonderful Life', value: 'It\'s a Wonderful Life' },
    { label: 'Star Wars: Episode IV - A New Hope', value: 'Star Wars: Episode IV - A New Hope' },
    { label: 'Saving Private Ryan', value: 'Saving Private Ryan' },
    { label: 'Spirited Away', value: 'Spirited Away' },
    { label: 'The Green Mile', value: 'The Green Mile' },
    { label: 'Interstellar', value: 'Interstellar' },
    { label: 'Parasite', value: 'Parasite' },
    { label: 'Léon: The Professional', value: 'Léon: The Professional' },
    { label: 'The Usual Suspects', value: 'The Usual Suspects' },
    { label: 'Harakiri', value: 'Harakiri' },
    { label: 'The Lion King', value: 'The Lion King' },
    { label: 'Back to the Future', value: 'Back to the Future' },
    { label: 'The Pianist', value: 'The Pianist' },
    { label: 'Terminator 2: Judgment Day', value: 'Terminator 2: Judgment Day' },
    { label: 'American History X', value: 'American History X' },
    { label: 'Modern Times', value: 'Modern Times' },
    { label: 'Psycho', value: 'Psycho' },
    { label: 'Gladiator', value: 'Gladiator' },
    { label: 'City Lights', value: 'City Lights' },
    { label: 'The Departed', value: 'The Departed' },
    { label: 'The Intouchables', value: 'The Intouchables' },
    { label: 'Whiplash', value: 'Whiplash' },
    { label: 'The Prestige', value: 'The Prestige' },
    { label: 'Grave of the Fireflies', value: 'Grave of the Fireflies' },
    { label: 'Casablanca', value: 'Casablanca' },
    { label: 'Once Upon a Time in the West', value: 'Once Upon a Time in the West' },
    { label: 'Rear Window', value: 'Rear Window' },
    { label: 'Cinema Paradiso', value: 'Cinema Paradiso' },
    { label: 'Alien', value: 'Alien' },
    { label: 'Apocalypse Now', value: 'Apocalypse Now' },
    { label: 'Memento', value: 'Memento' },
    { label: 'Raiders of the Lost Ark', value: 'Raiders of the Lost Ark' },
    { label: 'Glory', value: 'Glory' },
    { label: 'The Great Dictator', value: 'The Great Dictator' },
    { label: 'Django Unchained', value: 'Django Unchained' },
    { label: 'The Lives of Others', value: 'The Lives of Others' },
    { label: 'The Shining', value: 'The Shining' },
    { label: 'Paths of Glory', value: 'Paths of Glory' },
    { label: 'WALL·E', value: 'WALL·E' },
    { label: 'Sunset Boulevard', value: 'Sunset Boulevard' },
    { label: 'Witness for the Prosecution', value: 'Witness for the Prosecution' },
    { label: 'The Dark Knight Rises', value: 'The Dark Knight Rises' },
    { label: 'Princess Mononoke', value: 'Princess Mononoke' },
    { label: 'Oldboy', value: 'Oldboy' },
    { label: 'Once Upon a Time in America', value: 'Once Upon a Time in America' },
    { label: 'Aliens', value: 'Aliens' },
    { label: 'Das Boot', value: 'Das Boot' },
    { label: 'Citizen Kane', value: 'Citizen Kane' },
    { label: 'Vertigo', value: 'Vertigo' },
    { label: 'North by Northwest', value: 'North by Northwest' },
    { label: 'Star Wars: Episode VI - Return of the Jedi', value: 'Star Wars: Episode VI - Return of the Jedi' },
    { label: 'Reservoir Dogs', value: 'Reservoir Dogs' },
    { label: 'Braveheart', value: 'Braveheart' },
];

export default topMovies;